### ISSUE TITLE
Exportify has encountered an unexpected error (5XX) 

### ISSUE THREAD

**Issue by danseare** [watsonbox/exportify#142] opened 2023-04-22 16:23 UTC
Consistently getting this error for several days. When I go to the Spotify Web API Status page it reports "All Systems Operational". I suspect the most likely culprit is the very large number of liked songs I have  in my account (28,375). I haven't yet tried "unliking" a portion of them but will try when time permits.

**Comment by danseare** [comment] 2023-04-29 00:42
On 2023.04.15 I was able to do a full export when I had 28,276 liked songs. 
Shortly after that with 28,455, Exortify was timing out at log in.
On 4/24, I decreased the number of likes to 19,999 and was finally able to log on. Increasing to 20,000 reintroduced the same login time out I experienced with 28,455.
Although I was able to login with 19,999 liked songs, when I initiated an export I saw that same message about 5xx error on Spotify’s side.
To get exporting to work I had to decrease the number of liked songs to 10,999. At 11,000, initiating an export reintroduced the message about 5xx error on Spotify’s side.
One more data point: I am seeing a very similar issue on https://www.nativenoise.co.za/spotify/follow-all-artists.

**Comment by flawedgun** [comment] 2023-05-07 21:10
Oof.  Another data point: I've got over 24k songs liked and now I'm getting the error.  I used to use Exportify w/ no problem with ~22k-23k songs liked.  The other version of Exportify is still working for me, but that one doesn't allow you to export your liked song or to do a search for playlists.  Would love to see this fixed.

**Comment by watsonbox** [comment] 2023-05-12 16:29
I happened to see this one first, but I note that it's actually a duplicate of https://github.com/watsonbox/exportify/issues/140, where as @erricrice suggests, there's no harm in increasing the wait time a little to see if it helps... I'll pick that up over there.

**Closed by watsonbox** 2023-05-12 16:29 UTC
Labels: wontfix
