### ISSUE TITLE
500 Error with large volume of liked songs

### ISSUE THREAD

**Issue by the-groundsman** [watsonbox/exportify#150] opened 2023-11-28 11:24 UTC
Hi - I'm not very technical so forgive any ignorance.

I saw the issue with playlist size, but wanted to report a similar issue with liked songs. 

I got 500 error immediately after clicking get started, before any playlists were displayed in your webapp. This happened after "liking" a large number of songs in spotify (around 20,000). I was experimenting using "liked" for another app. Once Unliked in Spotify all was fine again.

Thank you very much for developing Exportify - for me it's an essential part of managing my music between local songs and Spotify.

**Comment by watsonbox** [comment] 2024-02-18 17:04
Duplicate of https://github.com/watsonbox/exportify/issues/140 I believe.

Thanks for the report, though - glad you find Exportify useful.

**Closed by watsonbox** 2024-02-18 17:04 UTC
Labels: duplicate
